[package]
name = "togen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.25"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
hound = "3.5"
hex = "0.4"
js-sys = "0.3"
